# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sonicsight_pb2 as sonicsight__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sonicsight_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SonicSightServiceStub(object):
    """──────────────────────────────────────────────
    Core Service
    ──────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessVideo = channel.stream_unary(
                '/sonicsight.SonicSightService/ProcessVideo',
                request_serializer=sonicsight__pb2.VideoChunk.SerializeToString,
                response_deserializer=sonicsight__pb2.InferenceResult.FromString,
                _registered_method=True)
        self.StreamProcess = channel.stream_stream(
                '/sonicsight.SonicSightService/StreamProcess',
                request_serializer=sonicsight__pb2.StreamChunk.SerializeToString,
                response_deserializer=sonicsight__pb2.StreamResult.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/sonicsight.SonicSightService/HealthCheck',
                request_serializer=sonicsight__pb2.Empty.SerializeToString,
                response_deserializer=sonicsight__pb2.HealthResponse.FromString,
                _registered_method=True)


class SonicSightServiceServicer(object):
    """──────────────────────────────────────────────
    Core Service
    ──────────────────────────────────────────────
    """

    def ProcessVideo(self, request_iterator, context):
        """Client streams raw video chunks → server returns inference results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamProcess(self, request_iterator, context):
        """Bidirectional streaming for near real-time processing
        Client streams continuous raw frames + audio
        Server streams back continuous separated audio + heatmaps
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SonicSightServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessVideo': grpc.stream_unary_rpc_method_handler(
                    servicer.ProcessVideo,
                    request_deserializer=sonicsight__pb2.VideoChunk.FromString,
                    response_serializer=sonicsight__pb2.InferenceResult.SerializeToString,
            ),
            'StreamProcess': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamProcess,
                    request_deserializer=sonicsight__pb2.StreamChunk.FromString,
                    response_serializer=sonicsight__pb2.StreamResult.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=sonicsight__pb2.Empty.FromString,
                    response_serializer=sonicsight__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sonicsight.SonicSightService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sonicsight.SonicSightService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SonicSightService(object):
    """──────────────────────────────────────────────
    Core Service
    ──────────────────────────────────────────────
    """

    @staticmethod
    def ProcessVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/sonicsight.SonicSightService/ProcessVideo',
            sonicsight__pb2.VideoChunk.SerializeToString,
            sonicsight__pb2.InferenceResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamProcess(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sonicsight.SonicSightService/StreamProcess',
            sonicsight__pb2.StreamChunk.SerializeToString,
            sonicsight__pb2.StreamResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sonicsight.SonicSightService/HealthCheck',
            sonicsight__pb2.Empty.SerializeToString,
            sonicsight__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
